# Generated by Django 4.2.1 on 2023-05-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendees", "0002_accountvo"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="has_account",
            field=models.BooleanField(null=True),
        ),
    ]
